### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by NecaX** [skellgreco/cially#81]
**Describe the bug**
Login don't work, even when the user is created in the database

**To Reproduce**
1º - Setup Cially v2 beta 3
2º - Create user, check the user is created in the database

<img width="1240" height="346" alt="Image" src="https://github.com/user-attachments/assets/a6544ec6-e9d9-400d-bc97-d8703c600e38" />

3º - Try to login, but the login failed

<img width="1136" height="458" alt="Image" src="https://github.com/user-attachments/assets/1f10190e-fb4d-4775-86c4-bffb1a1d4e2f" />

**Expected behavior**
The login works as expected

**Additional context**
Additionaly, you can bypass the login partially if use the URL http[s]://CIALLYURL/dashboard

<img width="1155" height="404" alt="Image" src="https://github.com/user-attachments/assets/8ac496b2-6998-4946-a4a7-fb2b05f745b1" />

**Comment by skellgreco** [comment]
Known issue. There seems like a problem between services communication while using Docker. That's what causes the bypass too

Investigating...

**Comment by skellgreco** [comment]
Hello there. 

Can you click the status button on the bottom of /dashboard page and share what it shows?

Thanks

**Comment by NecaX** [comment]
Hello,

It show all fine

<img width="1361" height="760" alt="Image" src="https://github.com/user-attachments/assets/a610448c-85a8-40dc-93ef-c26687989669" />

First, I had an error with API, but when I change in the API url in the .env file to use the port 3000, it works.

<img width="812" height="352" alt="Image" src="https://github.com/user-attachments/assets/bcd29318-5098-4a62-ba42-916ab3df5f2c" />

**Comment by NecaX** [comment]
Additionally, when I try to use the new "Retrieve Data" button, the website redirects to login, so it don't works.

**Comment by skellgreco** [comment]
Hello

Could you try the new beta and give me some feedback. Just update your .env and docker-compose files. For Pocketbase URL, try pasting the actual pocketbase URL (like http://your-domain:8090/)

Let me know if that works for you. If not, I will follow a different workaround and publish a new beta release.

Thanks!

**Comment by NecaX** [comment]
I recreate de containers and the volumes with the new beta, and the login works now (after fighting with the CORS header). 

I've seen that it's currently necessary for the connection to Pocketbase to be external, as you said. If you use Docker's internal URL, it doesn't work properly.

On the other hand, the "Retrieve data" function shows the following error:

<img width="1769" height="375" alt="Image" src="https://github.com/user-attachments/assets/4be15a10-862a-4da8-9410-f9b7d54691e7" />
And redirects to the login screen.

Thanks for all your work! It's an amazing tool.

**Comment by skellgreco** [comment]
Thanks for the feedback.

Please provide the following clarifications if possible:
- What do you mean by "fighting with CORS header"
- Regarding the "Retrieve Data" button, does that issue appears for other discord servers too? Also, is the discord server that you are trying to retrieve data from logged in the database? Let me know if you'd like instructions regarding how to check that :P
- Is the bypassing issue fixed now?

**Comment by NecaX** [comment]
> Thanks for the feedback.
> 
> Please provide the following clarifications if possible:
> 
> * What do you mean by "fighting with CORS header"
> * Regarding the "Retrieve Data" button, does that issue appears for other discord servers too? Also, is the discord server that you are trying to retrieve data from logged in the database? Let me know if you'd like instructions regarding how to check that :P
> * Is the bypassing issue fixed now?

- The CORS header problem was a joke about my infrastructure, don't worry jajaja
- The "Retrieve Data" issue occurs on all my servers. The server appears in the table "guilds" and new messages appear in the table "messages", but they are eliminated after a while and the "user_stats" table is updated.
- The bypassing issue persists in my tests

Edit: If you need some specific test, let me know and I'll help if I can.

**Comment by skellgreco** [comment]
Hello there!

I just published a 5th BETA Version which fixed the issues reported! Please update your `docker-compose.yaml` and let me know if the issues are fixed.

 Thanks!

**Comment by NecaX** [comment]
It seems to work now!. Thanks!
